### PR TITLE
Bump k8s libraries to 1.14.1

### PR DESCRIPTION
**Pull request by damemi**
This would allow us to bring in new features such as `+nullable` (see https://github.com/kubernetes-sigs/controller-tools/pull/180)

### CODE REVIEW

**Comment by damemi** [comment]
cc @sttts

**Comment by sttts** [comment]
@DirectXMan12 ptal

**Comment by damemi** [comment]
ping @droot could you take a look at this?

**Comment by DirectXMan12** [comment]
This should update go.mod now, no?

**Comment by sttts** [comment]
> This should update go.mod now, no?

Go mod is not supported by kube libs before 1.15.

**Comment by sttts** [comment]
Oh funny, there is Gopkg and go.mod.

**Comment by damemi** [comment]
Is there something I should run to update go.mod too? Think this was just the output of `dep ensure`

**Comment by DirectXMan12** [comment]
go.mod is updated with `go mod tidy` and `go get -u` when `GO111MODULE=on` is set (or you're outside Gopath).  Modules are the "canonical" form ATM, but we're maintaining a Gopkg.toml file (without updating vendor) to ensure we don't break users, since dep doesn't understand modules yet.

**Comment by DirectXMan12** [comment]
I need to add a README node

**Comment by damemi** [comment]
@DirectXMan12 okay, ran `go mod tidy` but don't see any updates in go.mod to the k8s libraries, that right?

**Comment by damemi** [comment]
Pushed commit for you to see

**Comment by sttts** [comment]
@DirectXMan12 @damemi what is blocking this?

**Comment by damemi** [comment]
Updated this with a `go get -u`

**Comment by DirectXMan12** [comment]
/hold

till #200

**Comment by sttts** [comment]
#200 merged.

**Comment by sttts** [comment]
@damemi looks like this needs a rebase.

**Comment by kragniz** [comment]
This now needs `Gopkg.lock` updating again?

**Comment by damemi** [comment]
Tried running the `go.mod` change before updating dep, hopefully passes this time

**Comment by damemi** [comment]
Closing for https://github.com/kubernetes-sigs/controller-tools/pull/204 which does the same thing

**Pull request closed without merging**
