### PR TITLE
:bug: Fix trivialVersions validation by processing each groupKind only once

### PR DESCRIPTION
**Pull request by sebgl**
Fixes https://github.com/kubernetes-sigs/controller-tools/issues/349.

FindKubeKinds may return duplicates if there are several versions of the
same groupKind for which we want to generate CRDs.
When combined with the trvialVersions option, which does mutate a
pointer of the corresponding object, we end up overriding the
top-level `validation` field with `nil`, resulting from the already
overridden schema of another version of the same GroupKind.

This commit fixes it by making sure FindKubeKinds does not return
duplicate entries.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Can you add a test for this, if possible?

**Comment by sebgl** [comment]
@DirectXMan12 I'll try to add a test 👍 
(this week is busy, I'll look at it next week)

**Comment by sebgl** [comment]
I'll create a separate PR (for easier review) to add integration tests for CRD generation based on the cronjob example.
Then add a trivial version test covering this PR.

**Comment by sebgl** [comment]
I plan to rebase this PR on https://github.com/kubernetes-sigs/controller-tools/pull/365 once https://github.com/kubernetes-sigs/controller-tools/pull/365 is merged. The rebase will [highlight differences in the integration tests YAML manifests](https://github.com/kubernetes-sigs/controller-tools/pull/365#discussion_r350404541).

**Pull request closed without merging**
