### PR TITLE
🏃 Remove status from generated CRD yaml

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
Currently generated CRD yamls have an empty status section. This pr will remove that.

crd-status

**Comment by tamalsaha** [comment]
This same pipeline can be used to remove the description fields to solve https://github.com/kubernetes-sigs/controller-tools/issues/288 and https://github.com/kubernetes-sigs/controller-tools/issues/257

Once we have `map[string]interface{}`, the description fields can be yanked.

**Comment by munnerz** [comment]
+1 to what you're doing here, but I wonder why the regular `omitempty` tags aren't already taking care of this.. 🙄 

Aside from my own curiosity though, this lgtm 😄

/lgtm

**Comment by DirectXMan12** [comment]
Those fields aren't properly marked as optional/omitempty  We actually *need* have them present for some kubernetes versions, otherwise client-side validation barfs.

**Comment by tamalsaha** [comment]
> We actually need have them present for some kubernetes versions, otherwise client-side validation barfs.

@DirectXMan12 , can you please tell me which version causes problem? I did not know that.

**Comment by DirectXMan12** [comment]
I don't recall off the top of my head, but I've definitely seen kubectls that exhibit the issue.  If you can't find one, I'll double check tomorrow.

**Comment by DirectXMan12** [comment]
hmm... it's also possible I'm misremembering, and it's that status, when present, gets generated incorrectly by default.  I'll play around a bit.

**Comment by liubog2008** [comment]
It's useful for server-side apply. Now status will be conflicted.

See http://k8s.io/docs/reference/using-api/api-concepts/#conflicts
Apply failed with 3 conflicts: conflicts with "kube-apiserver" using apiextensions.k8s.io/v1:
- .status.conditions
- .status.acceptedNames.kind
- .status.acceptedNames.plural

**Comment by liubog2008** [comment]
@DirectXMan12 @tamalsaha

**Pull request closed without merging**
