### PR TITLE
Add alpha command tree

### PR DESCRIPTION
**Pull request by jkev53**
Initial Commit
[Issue 74](https://github.com/kubernetes-sigs/controller-tools/issues/74)

### CODE REVIEW

**Comment by jkev53** [comment]
Adding an alpha feature requires the following 3 steps.
First add implementation files under the pkg/alpha directory. Here we add a feature alpha list
```
pkg/alpha/
└── list
    └── pkg
        └── util
            └── util.go
```
Second add the `cobra` command file under cmd/controller-scaffold/cmd/alpha/list.go
```
cmd/controller-scaffold/cmd/
├── alpha
│   └── list.go
├── alpha.go
├── api.go
├── project.go
├── root.go
└── stdin.go
``` 
Third add the cobra command to  cmd/controller-scaffold/cmd/alpha.go
```
func init() {
	rootCmd.AddCommand(AlphaCmd)
	AlphaCmd.AddCommand(alpha.ListCmd)
}
```
It is important that you do not change files outside of these locations with alpha features.

**Comment by droot** [comment]
@jkev53 I want to put this on hold since we aren't introducing any alpha command soon.

**Comment by droot** [comment]
Thanks @jkev53 for the PR. The PR help in validating the approach for introducing alpha command. Given that `pkg/scaffold` has been moved to kubebuilder repo and alpha command has been also added, I am closing this PR.

**Pull request closed without merging**
