### PR TITLE
[WIP] ✨ Add openapiv3 generator

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

⚠️ This only works with CRDv1 definitions.

### CODE REVIEW

**Comment by timothysc** [comment]
xref - https://github.com/kubernetes-sigs/kubebuilder/issues/1231

**Comment by vincepri** [comment]
Marked as a WIP to see if this this is what we want/need, I'll update the `testdata` once the final spec of this generator is finalized

**Comment by vincepri** [comment]
For folks that want to try it out:

- Checkout this PR branch, you can use `gh pr checkout 465` if you have `gh` cli installed
- Run `go get ./...` to build the CLI
- Run `controller-gen openapiv3:manifests=./config/crd/bases paths=./api/... output:dir=./manifests` in a kubebuilder project.

**Comment by jjfeiler** [comment]
@vincepri I'm getting a SIGSEGV when I try to run this as you suggested above `controller-gen openapiv3:manifests=./config/crd/bases paths=./api/... output:dir=./manifests` because version.Schema is nil on pkg/openapiv3/gen.go:74. Not sure where that Schema should be coming from in this case.

**Pull request closed without merging**
