### PR TITLE
:sparkles: Factor code common to both types of webhooks into methods

### PR DESCRIPTION
**Pull request by marun**
**NOTE** This PR is not ready for review until #276 merges.

I was independently updating deps to kube 1.16 per the request of @sttts and only near completion noticed #276.  Since I had already refactored the code in keeping with a [request](https://github.com/kubernetes-sigs/controller-tools/pull/276#discussion_r315394569) by @DirectXMan12, I'm posting those changes on top of #276 in case they are useful.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
#276 merged.  Can you rebase this PR?

**Comment by marun** [comment]
Rebased

**Comment by sttts** [comment]
:+1:

**Pull request merged**
