### PR TITLE
✨ Upgrade to go 1.19 and fix CI

### PR DESCRIPTION
**Pull request by Jefftree**
Upgrade to go 1.19 and fix CI to pass.

The CI is currently broken on the latest master branch (See https://github.com/kubernetes-sigs/controller-tools/pull/720 and other PRs in the open PRs section.)

Steps:
```
Changed go.mod to 1.19
Upgraded golangci-lint to latest version (1.49.0)

go mod tidy
gofmt -s -w .
```

### CODE REVIEW

**Comment by Jefftree** [comment]
/cc @camilamacedo86 
Is this something you can help with looking at? Thanks!

**Review by varshaprasad96 — APPROVED** [review]
/ok-to-test
/lgtm

**Review by camilamacedo86 — APPROVED** [review]
that shows fine for me 🥇 

/approved

**Comment by camilamacedo86** [comment]
closes: https://github.com/kubernetes-sigs/controller-tools/pull/713/files

**Comment by tamalsaha** [comment]
Could you please cut a release with the 1.25 deps?

**Pull request merged**
