### PR TITLE
🐛 fix windows filepath compatibility

### LINKED ISSUE #152: Util funcs do not correctly handle windows paths
This issue was found in an attempt to run kubebuilder on Windows.

As an example, assume a windows GOPATH of `C:\Whisk\knative\testevtsrc` with the complete project folder being `C:\Whisk\knative\testevtsrc\src\github.ibm.com\mdeuser\test-event-source`

Some of the pkg\crd\util\util.go funcs, such as DirToGoPkg, do not correctly handle the UNC path separators.  Using the above example, DirToGoPkg would produce the package prefix string
```
github.ibm.com\mdeuser\test-event-source
```
which kubebuilder would use to produce import statements having incorrect separators
```
github.ibm.com\mdeuser\test-event-source/pkg/apis
github.ibm.com\mdeuser\test-event-source/pkg/controller
github.ibm.com\mdeuser\test-event-source/pkg/webhook
```

Mildly related to https://github.com/kubernetes-sigs/kubebuilder/issues/300

### PR DESCRIPTION
**Pull request by alexeldeib**
Fixes #152, enables Kubebuilder Windows releases.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
It seems like you missed a few (there's a couple of spots that're still `path.Join`)

**Comment by alexeldeib** [comment]
@DirectXMan12 I took the slimmest possible cut to make this functional. Is it safe to assume we'd like to align all of these to `filepath` and not `path`? I'll align the rest if so.

**Comment by alexeldeib** [comment]
Looks like there were weren't too many others anyway.

**Comment by alexeldeib** [comment]
Per https://github.com/kubernetes-sigs/kubebuilder/pull/661#discussion_r273262411, I'm going to revert to the initial cut using fewer filepath calls. I don't see a point switching back and forth on filepath separators except where it's necessary on index checks, package imports, and file reads. 

Maybe I should really be aligning the `strings.HasPrefix()` calls + paths at the same time to make it a non-issue?

**Comment by alexeldeib** [comment]
@DirectXMan12 let me know the preferred route on this and I can implement it. Sorry to nag you, would love to get full releases of kubebuilder enabled for windows 😄

**Comment by alexeldeib** [comment]
Nice catch, fixed on the `os.Stat`.

**Comment by DirectXMan12** [comment]
thanks!

**Pull request merged**
