### PR TITLE
✨ bump k8s to v1.25.0

### LINKED ISSUE #711: Bump k8s to Kubernetes v1.25
Bump K8s version to v1.25

I will work on the issue once we have the **k8s v1.25 release.**

### PR DESCRIPTION
**Pull request by laxmikantbpandhare**
Update k8s versions to v1.25.0

This will fix #711

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Comment by laxmikantbpandhare** [comment]
@alvaroaleman @vincepri Could you please take a look into it.

**Review by alvaroaleman — APPROVED** [review]

**Comment by lucacome** [comment]
Would it be possible to have a release with this and https://github.com/kubernetes-sigs/controller-tools/pull/722 ? Thanks!

**Pull request merged**
