### PR TITLE
✨  update flect library to v0.2.0

### PR DESCRIPTION
**Pull request by pgier**
Minor improvements to pluralization rules including inching ever closer to correctly pluralizing 'Prometheus'

### CODE REVIEW

**Comment by mcristina422** [comment]
>including correctly pluralizing 'Prometheus'

v0.2.0 says it's `prometheuses` but according to prometheus the correct plural of `Prometheus` is `Prometheis`. 
https://prometheus.io/docs/introduction/faq/#what-is-the-plural-of-prometheus

**Comment by DirectXMan12** [comment]
lol.  @mcristina422 I've updated the PR description to reflect that.

/lgtm
/approve

**Comment by pgier** [comment]
@mcristina422 I did consider using the Greek plural as described in the video :smiley: , but went with the simpler/more common english plural since Bjorn seems to recommend that at the end, and it's what we had been using in prometheus-operator.

**Comment by DirectXMan12** [comment]
can we have a ld flag? `-ldflags "-X 'github.com/gobuffalo/flect.ProfoundlyPedanticPrometheusPlural=true'`

**Comment by DirectXMan12** [comment]
(that's a joke, just to clarify)

**Pull request merged**
