### PR TITLE
Remove scaffold pkg and test project

### PR DESCRIPTION
**Pull request by mengqiy**

### CODE REVIEW

**Comment by Liujingfang1** [comment]
Is the plan to add this to kubebuilder?

**Comment by mengqiy** [comment]
> Is the plan to add this to kubebuilder?

Yes. There will be a PR for that shortly

**Comment by mengqiy** [comment]
Right. It is deleted in https://github.com/kubernetes-sigs/controller-tools/pull/93/files#diff-59d90b4ae2a1649c75c68b352dcb3a49

**Comment by mengqiy** [comment]
PTAL
https://github.com/kubernetes-sigs/kubebuilder/pull/433 has been merged.

**Pull request merged**
