### PR TITLE
Don't gitignore generated files under vendor

### PR DESCRIPTION
**Pull request by justinsb**
Otherwise this breaks build from a checkout

### CODE REVIEW

**Comment by pwittrock** [comment]
Nice catch.

**Comment by pwittrock** [comment]
Can you also update the template that generates this here:

**Comment by droot** [comment]
@justinsb checking if you plan to update the template for tests to pass ?

**Comment by droot** [comment]
These changes were merged in with this PR https://github.com/kubernetes-sigs/controller-tools/pull/43 , so closing it.

**Pull request closed without merging**
