### PR TITLE
🏃Move pwittrock from emeritus approvers to approvers

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by pwittrock** [comment]
cc @mengqiy @droot @DirectXMan12

**Comment by DirectXMan12** [comment]
/approve
/lgtm
/hold

holding just to give anyone else a chance to comment, but this is fine by me.  Welcome back :tada: !

**Comment by DirectXMan12** [comment]
will merge tomorrow

**Comment by pwittrock** [comment]
Thanks @DirectXMan12 !

**Pull request merged**
