### PR TITLE
:bug: Handling Identical Kubebuilder Annotations in Different CRs with * Verbs

### PR DESCRIPTION
**Pull request by OdedViner**
#1077

### CODE REVIEW

**Comment by sbueringer** [comment]
Let's add some test coverage. You can take a look at https://github.com/kubernetes-sigs/controller-tools/pull/1045/files to see how this can be done

**Comment by OdedViner** [comment]
> Let's add some test coverage. You can take a look at https://github.com/kubernetes-sigs/controller-tools/pull/1045/files to see how this can be done

done

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
