### PR TITLE
✨feature(master): support  mutating name and validating name for webhook

### PR DESCRIPTION
**Pull request by cuisongliu**
Hello Kubernetes Community!

This PR support customize ValidatingWebhookConfiguration and MutatingWebhookConfiguration name.

ex:

```controller-gen  webhook:mutatingName=mutating-config,validatingName=validating-config```

Have a nice day

### CODE REVIEW

**Comment by munnerz** [comment]
This code seems correct, but it'd be good to understand the actual motivation behind this change. Would a kustomize overlay be more appropriate for renaming these resources, rather than markers passed to `controller-gen`? Is there a reason this would _not_ suit your use case?

**Comment by munnerz** [comment]
(also: welcome to the project! 😄)

**Comment by cuisongliu** [comment]
I think the kustomize is override the  additional attributes, is not override like name  the main feild.

**Pull request closed without merging**
