### PR TITLE
✨ add sideEffects parameter for webhooks

### PR DESCRIPTION
**Pull request by sethp-nr**
Allows setting sideEffects via annotation. 

Ultimately I'm looking at https://github.com/kubernetes-sigs/cluster-api/issues/2851, and declaring the sideEffects in the code seemed clearest to me.

### CODE REVIEW

**Comment by mengqiy** [comment]
Code LGTM.
Can you please add a small test for it?
Presumably, you can do something similar to [CRD](https://github.com/kubernetes-sigs/controller-tools/tree/master/pkg/crd/testdata) and [deepcopy](https://github.com/kubernetes-sigs/controller-tools/tree/master/pkg/deepcopy/testdata), which have the test read in input go files under testdata directory and then compare the result with the golden under testdata directory.

**Comment by sethp-nr** [comment]
Test added, let me know what you think!

**Comment by vincepri** [comment]
LGTM

**Pull request merged**
