### PR TITLE
🏃 Bump k8s.io dependencies to v0.27.1

### PR DESCRIPTION
**Pull request by furkatgofurov7**
Signed-off by: Furkat Gofurov (furkat.gofurov@suse.com)

v1.27 is out so bumping k8s.io related dependencies to the latest version of k8s.

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by vincepri** [comment]
@furkatgofurov7 can you rebase?

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 can you rebase?

Sure, on it

**Comment by furkatgofurov7** [comment]
@vincepri done

**Pull request merged**
