### PR TITLE
⚠ bump to kubernetes 1.22.1, remove support for legacy v1beta1 CRDs and webhooks

### PR DESCRIPTION
**Pull request by joelanford**
This PR bumps controller-tools k8s dependencies to 1.22.1

This is a breaking change. It removes support for v1beta1 CRDs and webhooks. These APIs are no longer served in 1.22.

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm 

Great 👍

**Review by alvaroaleman — APPROVED** [review]
/lgtm

**Comment by alvaroaleman** [comment]
/hold
failure is genuine, there is some dead code left

**Comment by camilamacedo86** [comment]
Hi @alvaroaleman, 

Yes. That fails with the master rebase only. So, that seems that was missing a rebase,  

Hi @joelanford, 

Thank you to push the changes.

**Pull request merged**
