### PR TITLE
✨  feature(master): support  mutating name and validating name for webhook

### PR DESCRIPTION
**Pull request by cuisongliu**
Hello Kubernetes Community!

This PR support customize  `ValidatingWebhookConfiguration`  and  `MutatingWebhookConfiguration` name.

ex: 
```shell

controller-gen  webhook:mutatingName=mutating-config,validatingName=validating-config

```

Have a nice day

### CODE REVIEW

**Comment by rdeusser** [comment]
Any update on this? It would be really nice to have so I don't have to go through and change the name manually.

**Comment by cuisongliu** [comment]
@vincepri  hi, this pr is pending. who can  review  this pr ? thanks.

**Comment by zhangxiaoyu-zidif** [comment]
please squash the commit first, and cc @mengqiy  PTAL

**Pull request closed without merging**
