### PR TITLE
✨ Add kubebuilder:label CRD marker to add labels

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

/assign @gerred @DirectXMan12

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Context: we've resisted doing this so far, since it's something that's generally pretty easy to do with kustomize and friends, and it's not really generally an attribute inherent to the CRD (i.e. it's something you might want to change w/o changing your Go code).

What's the motivating usecase here?

/hold

**Comment by vincepri** [comment]
Adding the marker allows for the CRDs in `crd/bases` to be populated with the label, rather than using kustomize to do add the label (which yeah it's pretty straightforward).

This is useful in `envtest` for example, we require a specific label to be present on the CRD when parsing object references. 

This isn't a release blocker for us, we found another way (hardcode a test CRD).

**Comment by DirectXMan12** [comment]
I think this generally encourages things that are bad patterns IMO, and the workarounds are pretty easy (kustomize, loading manually and setting the field, using a client to set the field, etc), so I'd prefer to not do this.

**Comment by vincepri** [comment]
Sounds good to me, thanks for providing an explanation.

/close

**Pull request closed without merging**
