### PR TITLE
⚠Change autogenerated / do not edit comment in deepcopy files

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

This PR changes the comment warning users to `DO NOT EDIT` and makes it similar to other k8s generation tools. I stumbled upon this while running verify-boilerplate from k/k, which looks for "DO NOT EDIT" in a file to consider it autogenerated.

### CODE REVIEW

**Comment by chuckha** [comment]
For context: https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.py#L211

This is copied around to other projects and has this regex hardcoded.

**Comment by DirectXMan12** [comment]
can you change helpgen (cmd/helpgen) too?  It's just for internal use, might might as well be consistent.  Otherwise LGTM.

**Comment by vincepri** [comment]
@DirectXMan12 Done! I also ran go generate to regen the other files

**Pull request merged**
