### PR TITLE
⚠ Bump to Go 1.17, k8s.io v1.23-alpha4

### PR DESCRIPTION
**Pull request by sbueringer**
Depends on Go 1.17: https://github.com/kubernetes/test-infra/pull/24311

locally verified with go v1.17.2 + `make test-all`

### CODE REVIEW

**Comment by sbueringer** [comment]
Depends on https://github.com/kubernetes/test-infra/pull/24311

/hold

I'll try to upgrade controller-runtime too

**Review by vincepri — APPROVED** [review]

**Pull request merged**
